language: minimal
env: GO111MODULE=on
git:
  depth: 1
install:
  - eval "$(gimme)"
stages:
  - 'Lint'
  - 'Integration tests'
  - 'Test'
jobs:
  include:
    - stage: 'Lint'
      env: GIMME_GO_VERSION=1.12.x GIMME_OS=linux GIMME_ARCH=amd64
      before_script:
        - curl -sfL https://raw.githubusercontent.com/golangci/golangci-lint/master/install.sh| sh -s -- -b $(go env GOPATH)/bin v1.19.0
      script:
        - $GOPATH/bin/golangci-lint run --out-format=tab --tests=false optimizely/...
    - stage: 'Integration Tests'
      merge_mode: replace
      env: SDK=go
      cache: false
      language: minimal
      install: skip
      before_script:
        - mkdir $HOME/travisci-tools && pushd $HOME/travisci-tools && git init && git pull https://$CI_USER_TOKEN@github.com/optimizely/travisci-tools.git && popd
      script:
        - "$HOME/travisci-tools/fsc-trigger/trigger_fullstack-sdk-compat.sh"
      after_success: travis_terminate 0
    - &test
      stage: 'Test'
      env: GIMME_GO_VERSION=master GIMME_OS=linux GIMME_ARCH=amd64
      merge_mode: merge
      script:
        - go test -v -race ./... -coverprofile=profile.cov
    - <<: *test
      stage: 'Test'
      merge_mode: merge
      env: GIMME_GO_VERSION=1.8.x
      before_script:
        # GO module was not introduced earlier. need symlink to search in GOPATH
        - mkdir -p $GOPATH/src/github.com && pushd $GOPATH/src/github.com && ln -s $HOME/build/optimizely optimizely && popd
      script:
        - echo $GOPATH
        - echo $HOME
        - ls $HOME
        # -coverprofile was not introduced in 1.8
        - go test -v -race ./...
    - <<: *test
      stage: 'Test'
      merge_mode: merge
      env: GIMME_GO_VERSION=1.12.x
      before_script:      
        - go get github.com/mattn/goveralls
      after_success:
        - $GOPATH/bin/goveralls -coverprofile=profile.cov -service=travis-ci
